// <auto-generated />
using System;
using AlmacenesPorAhi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlmacenesPorAhi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624191754_Inicio")]
    partial class Inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlmacenesPorAhi.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Preferencias")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Rut")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApellidoMaterno = "Lopez",
                            ApellidoPaterno = "Gonzalez",
                            Direccion = "Av. Siempre Viva 742, Santiago",
                            Email = "maria.gonzalez@correo.cl",
                            Estado = "Activo",
                            FechaRegistro = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "",
                            Nombre = "Maria",
                            Preferencias = "Ropa de mujer, Accesorios",
                            Rut = "12.345.678-9",
                            Telefono = "+56 9 1234 5678"
                        },
                        new
                        {
                            Id = 2,
                            ApellidoMaterno = "Rojas",
                            ApellidoPaterno = "Muñoz",
                            Direccion = "Calle Los Olivos 154, Valparaiso",
                            Email = "carlos.munoz@correo.cl",
                            Estado = "Activo",
                            FechaRegistro = new DateTime(2024, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "",
                            Nombre = "Carlos",
                            Preferencias = "Electronica, Deportes",
                            Rut = "23.456.789-0",
                            Telefono = "+56 9 2345 6789"
                        },
                        new
                        {
                            Id = 3,
                            ApellidoPaterno = "Lopez",
                            Direccion = "Pasaje El Sol 890, Concepcion",
                            Email = "ana.lopez@correo.cl",
                            Estado = "Activo",
                            FechaRegistro = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "",
                            Nombre = "Ana",
                            Rut = "34.567.890-1",
                            Telefono = "+56 9 3456 7890"
                        },
                        new
                        {
                            Id = 4,
                            ApellidoPaterno = "Ramirez",
                            Estado = "Inactivo",
                            FechaRegistro = new DateTime(2024, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "",
                            Nombre = "Pedro",
                            Rut = "45.678.901-2",
                            Telefono = "+56 9 4567 8901"
                        },
                        new
                        {
                            Id = 5,
                            ApellidoMaterno = "Vargas",
                            ApellidoPaterno = "Torres",
                            Direccion = "Av. Del Mar 321, Viña del Mar",
                            Email = "sofia.torres@correo.cl",
                            Estado = "Activo",
                            FechaRegistro = new DateTime(2024, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Genero = "",
                            Nombre = "Sofia",
                            Preferencias = "Libros, Musica",
                            Rut = "PT-123456",
                            Telefono = "+56 9 5678 9012"
                        });
                });

            modelBuilder.Entity("AlmacenesPorAhi.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Poleras",
                            Color = "Blanco",
                            Descripcion = "Polera de algodon peinado, corte regular.",
                            Estado = "Activo",
                            FechaRegistro = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Polera basica algodon",
                            Precio = 7990m,
                            Stock = 25,
                            Talla = "M"
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Pantalones",
                            Color = "Azul",
                            Descripcion = "Jeans de mezclilla rigida, tiro medio.",
                            Estado = "Activo",
                            FechaRegistro = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Jeans recto clasico",
                            Precio = 19990m,
                            Stock = 12,
                            Talla = "L"
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Abrigos",
                            Color = "Negro",
                            Descripcion = "Chaqueta biker de cuero sintetico.",
                            Estado = "Activo",
                            FechaRegistro = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Chaqueta de cuero",
                            Precio = 49990m,
                            Stock = 5,
                            Talla = "L"
                        },
                        new
                        {
                            Id = 4,
                            Categoria = "Poleras",
                            Color = "Rojo",
                            Descripcion = "Polera con estampado grafico edicion limitada.",
                            Estado = "Agotado",
                            FechaRegistro = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Polera estampada",
                            Precio = 9990m,
                            Stock = 0,
                            Talla = "S"
                        },
                        new
                        {
                            Id = 5,
                            Categoria = "Accesorios",
                            Color = "Camel",
                            Descripcion = "Bufanda tejida, temporada anterior.",
                            Estado = "Descontinuado",
                            FechaRegistro = new DateTime(2023, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Bufanda de lana",
                            Precio = 12990m,
                            Stock = 8,
                            Talla = "M"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
